apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-redis-sentinel.labels" . | nindent 4 }}
  name: {{ include "haproxy-redis-sentinel.fullname" . }}
data:
  haproxy.cfg: |
    global
      stats socket /var/run/haproxy/haproxy.sock user haproxy group haproxy mode 660 level admin
      stats timeout 2m

    defaults
      mode tcp
      timeout connect {{ .Values.haproxy.timeouts.connect }}
      timeout server {{ .Values.haproxy.timeouts.server }}
      timeout client {{ .Values.haproxy.timeouts.client }}
      {{- if .Values.haproxy.maxConn | kindIs "int" }}
      maxconn {{ .Values.haproxy.maxConn }}
      {{- end }}

    frontend livez
      bind *:8888
      mode http
      monitor-uri /livez
      option      dontlognull

    frontend readyz
      bind *:8889
      mode http
      monitor-uri /readyz
      monitor fail if { nbsrv(redis_master_server) eq 0 }
      option      dontlognull

    {{ if .Values.haproxy.stats.enabled -}}
    frontend stats
      bind *:8404
      mode http
      stats enable
      stats uri /
      {{- if .Values.haproxy.stats.metrics.enabled }}
      http-request use-service prometheus-exporter if { path /metrics }
      {{- end }}
      stats refresh {{ .Values.haproxy.stats.refresh }}
    {{- end }}

    frontend redis_master
      bind *:6379
      default_backend redis_master_server

    backend redis_master_server
        balance source
        hash-type consistent

