apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "haproxy-redis-sentinel.labels" . | nindent 4 }}
  name: {{ include "haproxy-redis-sentinel.fullname" . }}
data:
  haproxy.cfg: |
    global
      stats socket /var/run/haproxy/haproxy.sock user haproxy group haproxy mode 660 level admin
      stats timeout 2m

    {{- if .Values.haproxy.stats.enabled }}

    frontend stats
      bind *:8404
      mode http
      stats enable
      stats uri /
      {{- if .Values.haproxy.stats.metrics.enabled }}
      http-request use-service prometheus-exporter if { path /metrics }
      {{- end }}
      stats refresh {{ .Values.haproxy.stats.refresh }}
    {{- end }}

    frontend redis_master
      bind *:6379
      default_backend redis_master

    backend redis_master
        balance source
        hash-type consistent

