apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "haproxy-redis-sentinel.labels" . | nindent 4 }}
  name: {{ include "haproxy-redis-sentinel.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "haproxy-redis-sentinel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "haproxy-redis-sentinel.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: haproxy
          resources:
{{ toYaml .Values.haproxy.resources | default "{}" | indent 11 }}
          image: {{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy }}
          volumeMounts:
            - name: haproxy-socket
              mountPath: /var/run/haproxy/
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
          ports:
            {{- if .Values.haproxy.stats.enabled }}
            - name: stats
              containerPort: 8404
              protocol: TCP
            {{- end }}
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: readyz
              containerPort: 8889
              protocol: TCP
            - name: livez
              containerPort: 8888
              protocol: TCP
          readinessProbe:
            httpGet:
              port: readyz
              path: /readyz
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: livez
              path: /livez
            initialDelaySeconds: 10
            periodSeconds: 3
          securityContext:
            runAsUser: 0

        - name: haproxy-redis-sentinel
          resources:
{{ toYaml .Values.haproxyRedisSentinel.resources | default "{}" | indent 11 }}
          image: {{ .Values.haproxyRedisSentinel.image.repository }}:{{ .Values.haproxyRedisSentinel.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.haproxyRedisSentinel.image.pullPolicy }}
          env:
            - name: SENTINEL_PASSWORD
              value: {{ tpl (.Values.haproxyRedisSentinel.sentinel.password | quote) . }}
            - name: SENTINEL_HOST
              value: {{ tpl .Values.haproxyRedisSentinel.sentinel.host . }}
            - name: SENTINEL_PORT
              value: {{ tpl (.Values.haproxyRedisSentinel.sentinel.port | quote) . }}
            - name: MASTER_NAME
              value: {{ tpl .Values.haproxyRedisSentinel.sentinel.masterName . }}
            - name: HAPROXY_BACKEND
              value: redis_master_server
          volumeMounts:
            - name: haproxy-socket
              mountPath: /var/run/haproxy/

      volumes:
        - name: haproxy-socket
          emptyDir: {}
        - name: haproxy-config
          configMap:
            name: {{ include "haproxy-redis-sentinel.fullname" . }}
