apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "haproxy-redis-sentinel.labels" . | nindent 4 }}
  name: {{ include "haproxy-redis-sentinel.fullname" . }}
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
    - port: {{ .Values.haproxy.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- if .Values.haproxy.stats.enabled }}
    - port: {{ .Values.haproxy.service.statsPort }}
      targetPort: stats
      protocol: TCP
      name: stats
    {{- end }}
  sessionAffinity: ClientIP
  selector:
    {{- include "haproxy-redis-sentinel.selectorLabels" . | nindent 4 }}
